service: firebase-cron-service

provider:
  region: eu-west-1
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 5
  environment:
    CONFIG: ${file(./config.json.config)}
    FIREBASE_PATH: gardenLights
    SERVICE_ACCOUNT_KEY: ${file(./service-account-key.json.config)}

functions:
  set:
    handler: src/index.set
    events:
      - schedule:
          rate: cron(0 15 * * ? *)
          input:
            data: true
      - schedule:
          rate: cron(30 20 * * ? *)
          input:
            data: false

  toggle:
    handler: src/index.toggle
    events:
      - iot:
          sql: "SELECT * FROM 'iotbutton/${self:custom.iotThingDSN}'"

resources:
  Resources:
    IoTThing:
      Type: AWS::IoT::Thing
      Properties:
        ThingName:
          Fn::Join:
            - ''
            - - iotbutton_
              - ${self:custom.iotThingDSN}

    IoTPolicy:
      Type: AWS::IoT::Policy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action: iot:Publish
            Effect: Allow
            Resource:
              Fn::Join:
                - ''
                - - 'arn:aws:iot:'
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - ":topic/iotbutton/"
                  - ${self:custom.iotThingDSN}

    IoTPolicyPrincipalAttachment:
      Type: AWS::IoT::PolicyPrincipalAttachment
      Properties:
        PolicyName:
          Ref: IoTPolicy
        Principal: ${self:custom.iotThingCertARN}

    IoTThingPrincipalAttachment:
      Type: AWS::IoT::ThingPrincipalAttachment
      Properties:
        Principal: ${self:custom.iotThingCertARN}
        ThingName:
          Ref: IoTThing

plugins:
  - serverless-webpack

custom:
  iotThingDSN: ${file(./iot-dash-certs/iot-thing-dsn.txt)}
  iotThingCertARN: ${file(./iot-dash-certs/iot-thing-cert-arn.txt)}

  webpack:
    includeModules: true
