service: firebase-cron-service

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 5
  environment:
    CONFIG: ${file(./config.json)}
    SERVICE_ACCOUNT_KEY: ${file(./service-account-key.json)}

functions:
  hello:
    handler: src/index.handler
    events:
      - schedule:
          rate: cron(0 15 * * ? *)
          input:
            path: gardenLights
            data: true
      - schedule:
          rate: cron(30 20 * * ? *)
          input:
            path: gardenLights
            data: false
      - iot:
          sql: "SELECT * FROM 'garden_lights'"

plugins:
  - serverless-webpack

custom:
  webpack:
    includeModules: true
